# Generated by Django 2.1.5 on 2019-03-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regloginformapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistartionData',
            new_name='RegistrationData',
        ),
    ]
